# ~ MiniJoin ~
# • Developed by InitSync | v1.0.0
# • MiniMessage Support!
# ~~~~~~~~~~
# Documentation:
#   MiniMessage: https://docs.adventure.kyori.net/minimessage/format.html
#   MiniMessage Viewer: https://webui.adventure.kyori.net
#   MiniJoin Actions: https://github.com/InitSync/MiniJoin
# ~~~~~~~~~~
config:
  # Plugin Prefix.
  prefix: "<gradient:blue:aqua>MiniJoin</gradient> <dark_gray><b>></b>"

  sounds:
    # Allow replay sounds?
    allow: true

    # Sounds ID´s.
    no-perm: ENTITY_ITEM_BREAK
    reload: UI_BUTTON_CLICK

  join-quit:
    # Allow use Join and Quit formats?
    # Else will be use the default format for servers.
    allow: true

    # Allow send the motd to join?
    allow-motd: true

    # Welcome User Message.
    motd:
      - "<b>"
      - "<gradient:aqua:white>               ServerName Network"
      - "<green>             Welcome to the Server!"
      - "<b>"
      - "<white> Remember invite to your <yellow>Friends and Enjoy!"
      - "<b>"
      - "<gradient:yellow:gold>            Social Networks</gradient> <gray>(Do Click)"
      - "<gradient:green:blue><hover:show_text:'<yellow>Click to get the link!'><click:open_url:'store.com/yourserver'>         Store • </click><hover:show_text:'<yellow>Click to get the link!'><click:open_url:'yourserver.com'>Web • </click><hover:show_text:'<yellow>Click to get the link!'><click:open_url:'twitter.com/@Yourserver'>Twitter • </click><hover:show_text:'<yellow>Click to get the link!'><click:open_url:'discord.io/yourserver'>Discord</click></gradient>"
      - "<b>"

    # Groups.
    groups:
      default:
        # Group Join Message.
        join: "<gray><hover:show_text:'<gray>IGN: <yellow><player_name><br><gray>Rank: <yellow>User<br><gray>Level: <yellow><player_level><br><br><gold>Click to send a message!'><click:suggest_command:'/msg <player_name>'><player_name></click></gray> <dark_gray><b>></b> <gray>Has joined to server!"

        # Group Join Actions.
        join-actions:
          - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP;1;1"

        # Group Quit Message.
        quit: "<gray><player_name> <dark_gray><b>></b> <gray>If has left the server!"
      admin:
        join: "<gradient:red:dark_red>%vault_prefix%</gradient> <white><hover:show_text:'<gray>IGN: <yellow><player_name><br><gray>Rank: <gradient:red:dark_red>%vault_prefix%</gradient><br><gray>Level: <yellow><player_level><br><br><gold>Click to send a message!'><click:suggest_command:'/msg <player_name>'><player_name></click></white> <dark_gray><b>></b> <yellow>Has joined to server!"
        join-actions:
          - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP;1;1"
        quit: "<gradient:red:dark_red>%vault_prefix%</gradient> <white><player_name> <dark_gray><b>></b> <yellow>If has left the server!"

messages:
  no-perm: "<prefix> <gradient:red:dark_red>You don't have permission for that!"
  no-command: "<prefix> <gradient:red:dark_red>That command has not been added!"

  help:
    - "<gradient:blue:aqua>MiniJoin</gradient> <dark_gray><b>|</b> <white>Available Commands:"
    - "<gray> - <gold><hover:show_text:'<gray><b>></b> <white>Shows the help<br><gray><b>></b> <white>plugin message.<br><br><yellow>Click to run the command!'><click:run_command:'/mj help'>/minijoin help</click></gold> <white>Shows this message."
    - "<gray> - <gold><hover:show_text:'<gray><b>></b> <white>Reloads the plugin<br><gray><b>></b> <white>configuration file.<br><br><yellow>Click to run the command!'><click:run_command:'/mj config'>/minijoin config</click></gold> <white>Reload the configuration."

  config: "<prefix> <gradient:yellow:gold>The plugin configuration has been reloaded successful!"